pipeline:
  restore-cache:
    image: plugins/s3-cache:1
    pull: true
    endpoint: http://thunderbuild.hxr.team:9001
    secrets: [ aws_access_key_id, aws_secret_access_key ]
    restore: true

  build:
    image: alpine
    commands:
      - mkdir dir1 dir2
      - touch dir1/file1 dir2/file2

  rebuild-cache:
    image: plugins/s3-cache:1
    pull: true
    endpoint: http://thunderbuild.hxr.team:9001
    secrets: [ aws_access_key_id, aws_secret_access_key ]
    rebuild: true
    mount:
      - dir1
      - dir2
    when:
      event: push
