version: '2'
volumes:
  pgdata: {}
services:
  pg:
    image: postgres
    extends:
      file: common.yml
      service: common
    volumes:
    - pgdata:/var/lib/postgresql/data
    environment:
    - POSTGRES_PASSWORD=secret
    ports:
    - "5432:5432"
