k9s:
  liveViewAutoRefresh: true
  portForwardAddress: localhost
  ui:
    skin: one-dark
    headless: true
    logoless: true
    crumbsless: true
    splashless: true
    noIcons: true
    defaultsToFullScreen: true
    reactive: true
  skipLatestRevCheck: true
  thresholds:
    cpu:
      critical: 90
      warn: 80
    memory:
      critical: 90
      warn: 80
