views:
  v1/pods:
    sortColumn: AGE:asc
    columns:
      - NAMESPACE
      - NAME
      - NODE IP:.status.hostIP
  v1/nodes:
    columns:
      - NAME
      - ZONE:.metadata.labels.topology\.kubernetes\.io/zone
      - INSTANCE TYPE:.metadata.labels.beta\.kubernetes\.io/instance-type
      - INTERNAL-IP|S
