add_newline = false
format = """\
  $directory\
  $git_branch\
  $git_commit\
  $git_state\
  $git_status\
  $terraform\
  $pulumi\
  $character\
  """
[directory]
truncation_length = 5
# truncate_to_repo = false
