command_timeout = 1000
add_newline = false
# A minimal left prompt
format = """$character"""
# move the rest of the prompt to the right
right_format = """$all"""
# A continuation prompt that displays two filled-in arrows
continuation_prompt = '▶▶ '