theme = "penumbra+"

[editor]
bufferline = "multiple"

[editor.soft-wrap]
enable = true

[editor.file-picker]
hidden = false

[editor.gutters.line-numbers]
min-width = 1

[editor.statusline]
left = ["file-absolute-path", "file-modification-indicator"]
center = []
right = []

[keys.normal]
q = ":x"
d = ["delete_selection_noyank"]

[keys.normal.space]
q = ":write-buffer-close"
x = ":toggle whitespace.render all none"
